sudo: false
language: node_js
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email:
    - jorgelca1205@gmail.com
node_js:
  - "8"
  - "10"
  - "12"
jobs:
  include:
    - install:
        - yarn
    - build:
        - yarn build
    - compile-icons:
        - yarn compile:icons
branches:
  only: master
